[workspace]
members = [
    "autheo-mlkem-kyber",
    "autheo-mldsa-dilithium",
    "autheo-mldsa-falcon",
    "autheo-pqc-core",
    "autheo-pqc-wasm",
]
resolver = "2"

[patch.crates-io]
home = { path = "vendor/home-0.5.5" }
