[package]
name = "autheo-pqc-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
autheo-pqc-core = { path = "../autheo-pqc-core" }
wee_alloc = { version = "0.4", default-features = false }
