[package]
name = "pqcnet-qace"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
genetic_algorithm = { version = "0.25.1", default-features = false }
